# Generated by Django 5.2.4 on 2025-07-27 06:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pays",
            fields=[
                (
                    "code_iso",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Pays",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Lieu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom_ville", models.CharField(max_length=200)),
                ("geoname_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lieux",
                        to="places.pays",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lieux",
                "ordering": ["nom_ville"],
                "unique_together": {("nom_ville", "pays")},
            },
        ),
        migrations.CreateModel(
            name="Voyage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "note",
                    models.IntegerField(
                        blank=True,
                        help_text="Note de 1 à 5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "lieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voyages",
                        to="places.lieu",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voyages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Voyages",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Favori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoris",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoris",
                        to="places.lieu",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Favoris",
                "ordering": ["-date_ajout"],
                "unique_together": {("utilisateur", "lieu")},
            },
        ),
    ]
