# Generated by Django 5.2.4 on 2025-08-10 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaVoyage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fichier", models.FileField(upload_to="voyages_medias/")),
                (
                    "type_media",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Vidéo")], max_length=10
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordre d'affichage"
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="places.voyage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média de voyage",
                "verbose_name_plural": "Médias de voyage",
                "ordering": ["ordre", "date_upload"],
            },
        ),
    ]
