# Generated by Django 5.2.4 on 2025-08-13 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_activite_noteactivite"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="adresse_precise",
            field=models.CharField(
                blank=True, help_text="Adresse précise de l'activité", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="activite",
            name="age_minimum",
            field=models.PositiveIntegerField(
                blank=True, help_text="Âge minimum requis (en années)", null=True
            ),
        ),
        migrations.AddField(
            model_name="activite",
            name="prix_estime",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix estimé en euros",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activite",
            name="reservation_requise",
            field=models.BooleanField(
                default=False, help_text="Réservation obligatoire"
            ),
        ),
        migrations.AddField(
            model_name="activite",
            name="transport_public",
            field=models.BooleanField(
                default=False, help_text="Accessible en transport en commun"
            ),
        ),
        migrations.AddField(
            model_name="activite",
            name="type_activite",
            field=models.CharField(
                choices=[
                    ("culture", "Culture & Patrimoine"),
                    ("nature", "Nature & Plein air"),
                    ("gastronomie", "Gastronomie"),
                    ("restauration_rapide", "Restauration rapide"),
                    ("sport", "Sport & Aventure"),
                    ("divertissement", "Divertissement"),
                    ("shopping", "Shopping"),
                    ("bien_etre", "Bien-être & Spa"),
                    ("autre", "Autre"),
                ],
                default="autre",
                help_text="Type d'activité",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MediaActivite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fichier", models.FileField(upload_to="activites_medias/")),
                (
                    "type_media",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Vidéo")], max_length=10
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordre d'affichage"
                    ),
                ),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="places.activite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média d'activité",
                "verbose_name_plural": "Médias d'activités",
                "ordering": ["ordre", "date_upload"],
            },
        ),
    ]
