# Generated by Django 5.2.4 on 2025-08-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="score_total",
            field=models.PositiveIntegerField(
                default=0, help_text="Score total de l'utilisateur"
            ),
        ),
    ]
